#include "TripleBuffer.h"
#include <assert.h>

int main()
{
	TRIPLE_BUFFER_TYPE(TestStruct, int);
	TRIPLE_BUFFER_NEW(it, TestStruct);

	/* Test 1 */

	*TRIPLE_BUFFER_WRITE_PTR(it) = 3;
	TRIPLE_BUFFER_FLIP_WRITER(it);

	TRIPLE_BUFFER_NEW_SNAP(it);
	assert(*TRIPLE_BUFFER_SNAP_PTR(it) == 3);

	/* Test 2 */

	*TRIPLE_BUFFER_WRITE_PTR(it) = 4;
	TRIPLE_BUFFER_FLIP_WRITER(it);
	*TRIPLE_BUFFER_WRITE_PTR(it) = 5;
	TRIPLE_BUFFER_FLIP_WRITER(it);
	*TRIPLE_BUFFER_WRITE_PTR(it) = 6;
	TRIPLE_BUFFER_FLIP_WRITER(it);

	TRIPLE_BUFFER_NEW_SNAP(it);

	*TRIPLE_BUFFER_WRITE_PTR(it) = 7;
	TRIPLE_BUFFER_FLIP_WRITER(it);
	*TRIPLE_BUFFER_WRITE_PTR(it) = 8;
	TRIPLE_BUFFER_FLIP_WRITER(it);

	assert(*TRIPLE_BUFFER_SNAP_PTR(it) == 6);

	/* Test 3 */

	TRIPLE_BUFFER_NEW_SNAP(it);
	assert(*TRIPLE_BUFFER_SNAP_PTR(it) == 8);

	TRIPLE_BUFFER_NEW_SNAP(it);
	assert(*TRIPLE_BUFFER_SNAP_PTR(it) == 8);

	return 0;
}
